name: Validate

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to the Registry
        uses: docker/login-action@v1
        with:
          username: ${{secrets.registry_username}}
          password: ${{secrets.registry_password}}
      
    
      - name: Build and Push the Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{secrets.registry_username}}/${{inputs.image_name}}:${{inputs.tag}}
